# -*- coding: utf-8 -*-
"""Generates every Android asset that follows the app style.

Run from the repository root after changing a palette:

    python scripts/style_assets/generate.py

It reads palettes.json (kept equal to kStylePalettes in
src/lib/core/theme/app_styles.dart by test/style_assets_test.dart) and writes,
for each style except linen (whose assets are the originals):

  - the launcher icon: adaptive foreground PNGs, legacy mipmap PNGs and the
    adaptive-icon XML, recoloured from the original artwork
  - the splash logo PNGs and a launch theme (values-v31/launch_styles.xml)
  - the home screen widget: a colour set (values/widget_style_colors.xml) and
    the shaped drawables that use it

Recolouring is a gradient map: every pixel's brightness is looked up on a ramp
of the style's own colours, so the artwork keeps every soft edge and highlight
and only its colours change. Needs Pillow.
"""
import io
import json
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
RES = os.path.join(ROOT, 'src', 'android', 'app', 'src', 'main', 'res')
DENSITIES = ['mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi']
HEADER = '<!-- Generated by scripts/style_assets/generate.py; do not edit by hand -->'


def rgb(hex_):
    hex_ = hex_.lstrip('#')
    return tuple(int(hex_[i:i + 2], 16) for i in (0, 2, 4))


def mix(a, b, t):
    return tuple(round(a[i] + (b[i] - a[i]) * t) for i in range(3))


WHITE = (255, 255, 255)

# Brightness of the original artwork's tones (measured on the linen icon): the
# darkest ink, the nodes and path, the glow around the nodes, the two ends of
# the background gradient, and the cream symbols
ANCHORS = [60, 85, 105, 175, 215, 232]


def ramp(p):
    primary, light, dark = rgb(p['primary']), rgb(p['primaryLight']), rgb(p['primaryDark'])
    if p['brightness'] == 'dark':
        # Dark ground, light path: the icon still reads on a dark home screen
        ground, card = rgb(p['surfaceVariant']), rgb(p['surface'])
        return [mix(primary, WHITE, 0.3), primary, mix(primary, ground, 0.5),
                ground, mix(card, ground, 0.5), rgb(p['background'])]
    return [mix(dark, (0, 0, 0), 0.25), dark, mix(dark, primary, 0.5),
            mix(light, primary, 0.38), mix(light, primary, 0.12), mix(WHITE, light, 0.5)]


def lookup(colours, lum):
    if lum <= ANCHORS[0]:
        return colours[0]
    for i in range(1, len(ANCHORS)):
        if lum <= ANCHORS[i]:
            t = (lum - ANCHORS[i - 1]) / (ANCHORS[i] - ANCHORS[i - 1])
            return mix(colours[i - 1], colours[i], t)
    return colours[-1]


def recolour(src, dst, colours):
    im = Image.open(src).convert('RGBA')
    table = [lookup(colours, l) for l in range(256)]
    out = Image.new('RGBA', im.size)
    out.putdata([
        (*table[int(0.299 * r + 0.587 * g + 0.114 * b)], a)
        for r, g, b, a in im.getdata()
    ])
    out.save(dst, optimize=True)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    io.open(path, 'w', encoding='utf-8', newline='\n').write(text)


def icons(style, p):
    colours = ramp(p)
    for d in DENSITIES:
        recolour(os.path.join(RES, 'drawable-' + d, 'ic_launcher_foreground.png'),
                 os.path.join(RES, 'drawable-' + d, 'ic_launcher_foreground_%s.png' % style), colours)
        recolour(os.path.join(RES, 'mipmap-' + d, 'ic_launcher.png'),
                 os.path.join(RES, 'mipmap-' + d, 'ic_launcher_%s.png' % style), colours)
        recolour(os.path.join(RES, 'drawable-' + d, 'splash_logo.png'),
                 os.path.join(RES, 'drawable-' + d, 'splash_logo_%s.png' % style), colours)
    write(os.path.join(RES, 'mipmap-anydpi-v26', 'ic_launcher_%s.xml' % style), '''<?xml version="1.0" encoding="utf-8"?>
%s
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@drawable/ic_launcher_background"/>
  <foreground>
      <inset
          android:drawable="@drawable/ic_launcher_foreground_%s"
          android:inset="16%%" />
  </foreground>
</adaptive-icon>
''' % (HEADER, style))


# The widget roles, from the palette. Linen keeps widget_colors.xml, which also
# has a night variant; the others are one fixed set each, since the style
# already says whether it is light or dark
def widget_roles(p):
    return {
        'background': p['background'],
        'border': p['border'],
        'text': p['textPrimary'],
        'accent': p['primary'],
        'muted': p['textTertiary'],
        'box': p['textSecondary'],
        'splash': p['background'],
    }


def widget_drawables(style):
    base = os.path.join(RES, 'drawable')
    for name in ['widget_background', 'widget_add_pill', 'widget_check_on', 'widget_check_off',
                 'widget_check_anim_on', 'widget_check_anim_off', 'widget_check']:
        text = io.open(os.path.join(base, name + '.xml'), encoding='utf-8').read()
        for role in ['background', 'border', 'accent', 'box']:
            text = text.replace('@color/widget_%s"' % role, '@color/widget_%s_%s"' % (role, style))
        for part in ['widget_check_on', 'widget_check_off', 'widget_check_anim_on', 'widget_check_anim_off']:
            text = text.replace('@drawable/%s"' % part, '@drawable/%s_%s"' % (part, style))
        text = text.replace('<?xml version="1.0" encoding="utf-8"?>\n',
                            '<?xml version="1.0" encoding="utf-8"?>\n%s\n' % HEADER, 1)
        write(os.path.join(base, '%s_%s.xml' % (name, style)), text)


def main():
    palettes = json.load(io.open(os.path.join(HERE, 'palettes.json'), encoding='utf-8'))
    styles = [s for s in palettes if s != 'linen']

    colours = []
    for style in styles:
        for role, value in widget_roles(palettes[style]).items():
            colours.append('    <color name="widget_%s_%s">%s</color>' % (role, style, value))
    write(os.path.join(RES, 'values', 'widget_style_colors.xml'),
          '<?xml version="1.0" encoding="utf-8"?>\n%s\n<resources>\n%s\n</resources>\n'
          % (HEADER, '\n'.join(colours)))

    themes = []
    for style in styles:
        parent = 'Theme.Black.NoTitleBar' if palettes[style]['brightness'] == 'dark' else 'Theme.Light.NoTitleBar'
        themes.append('''    <style name="LaunchTheme.%s" parent="@android:style/%s">
        <item name="android:windowSplashScreenBackground">@color/widget_splash_%s</item>
        <item name="android:windowSplashScreenAnimatedIcon">@drawable/splash_logo_%s</item>
        <item name="android:windowBackground">@color/widget_splash_%s</item>
    </style>''' % (style.capitalize(), parent, style, style, style))
    # For SplashScreen.setSplashScreenTheme (Android 13+), which MainActivity
    # calls with the style the next launch will wear
    write(os.path.join(RES, 'values-v31', 'launch_styles.xml'),
          '<?xml version="1.0" encoding="utf-8"?>\n%s\n<resources>\n%s\n</resources>\n'
          % (HEADER, '\n'.join(themes)))

    for style in styles:
        icons(style, palettes[style])
        widget_drawables(style)
    print('generated assets for', ', '.join(styles))


if __name__ == '__main__':
    main()
