package com.octofield.urniversity

import android.content.SharedPreferences

/**
 * The widget's colours and shapes for the app style the user wears
 * (system_design.md §3-R). Dart writes the style's name as `app_style` next to
 * the snapshot. Linen keeps the original resources, which also have a night
 * variant and so follow the system theme; every other style is one fixed set,
 * since the style itself already says light or dark.
 *
 * The *_<style> resources are generated by scripts/style_assets/generate.py.
 */
data class WidgetStyle(
    val background: Int,
    val addPill: Int,
    val checkOn: Int,
    val checkOff: Int,
    val checkSelector: Int,
    val text: Int,
    val accent: Int,
    val muted: Int,
) {
    companion object {
        const val KEY = "app_style"

        fun of(prefs: SharedPreferences): WidgetStyle = when (prefs.getString(KEY, null)) {
            "modern" -> WidgetStyle(
                R.drawable.widget_background_modern, R.drawable.widget_add_pill_modern,
                R.drawable.widget_check_on_modern, R.drawable.widget_check_off_modern,
                R.drawable.widget_check_modern,
                R.color.widget_text_modern, R.color.widget_accent_modern, R.color.widget_muted_modern,
            )
            "midnight" -> WidgetStyle(
                R.drawable.widget_background_midnight, R.drawable.widget_add_pill_midnight,
                R.drawable.widget_check_on_midnight, R.drawable.widget_check_off_midnight,
                R.drawable.widget_check_midnight,
                R.color.widget_text_midnight, R.color.widget_accent_midnight, R.color.widget_muted_midnight,
            )
            "sage" -> WidgetStyle(
                R.drawable.widget_background_sage, R.drawable.widget_add_pill_sage,
                R.drawable.widget_check_on_sage, R.drawable.widget_check_off_sage,
                R.drawable.widget_check_sage,
                R.color.widget_text_sage, R.color.widget_accent_sage, R.color.widget_muted_sage,
            )
            "ocean" -> WidgetStyle(
                R.drawable.widget_background_ocean, R.drawable.widget_add_pill_ocean,
                R.drawable.widget_check_on_ocean, R.drawable.widget_check_off_ocean,
                R.drawable.widget_check_ocean,
                R.color.widget_text_ocean, R.color.widget_accent_ocean, R.color.widget_muted_ocean,
            )
            "sakura" -> WidgetStyle(
                R.drawable.widget_background_sakura, R.drawable.widget_add_pill_sakura,
                R.drawable.widget_check_on_sakura, R.drawable.widget_check_off_sakura,
                R.drawable.widget_check_sakura,
                R.color.widget_text_sakura, R.color.widget_accent_sakura, R.color.widget_muted_sakura,
            )
            "mono" -> WidgetStyle(
                R.drawable.widget_background_mono, R.drawable.widget_add_pill_mono,
                R.drawable.widget_check_on_mono, R.drawable.widget_check_off_mono,
                R.drawable.widget_check_mono,
                R.color.widget_text_mono, R.color.widget_accent_mono, R.color.widget_muted_mono,
            )
            // Linen, or nothing written yet: the original look
            else -> WidgetStyle(
                R.drawable.widget_background, R.drawable.widget_add_pill,
                R.drawable.widget_check_on, R.drawable.widget_check_off,
                R.drawable.widget_check,
                R.color.widget_text, R.color.widget_accent, R.color.widget_muted,
            )
        }
    }
}
