import 'dart:convert';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/journal.dart';

class JournalNotifier extends StateNotifier<List<Journal>> {
  JournalNotifier() : super([]);

  String? _userId;
  SupabaseClient get _db => Supabase.instance.client;
  static const _localKey = 'guest_journals';
  static const _kForgotToWrite = '好像忘記什麼了......';
  bool get _isGuest => _userId == 'guest';

  Future<void> load(String userId) async {
    if (_userId == userId) return;
    _userId = userId;
    try {
      final rows = await _db
          .from('journals')
          .select()
          .eq('user_id', userId)
          .order('date', ascending: false);
      state = (rows as List<dynamic>)
          .map((r) => Journal.fromJson(r as Map<String, dynamic>))
          .toList();
      await _fillMissingDays();
    } catch (_) {
      _userId = null;
    }
  }

  Future<void> loadGuest() async {
    _userId = 'guest';
    final p = await SharedPreferences.getInstance();
    final json = p.getString(_localKey);
    if (json != null) {
      state = (jsonDecode(json) as List)
          .map((j) => Journal.fromJson(j as Map<String, dynamic>))
          .toList();
      await _fillMissingDays();
    } else {
      state = [];
    }
  }

  void _persistLocally() {
    SharedPreferences.getInstance().then((p) {
      p.setString(_localKey, jsonEncode(state.map((j) => j.toJson()).toList()));
    });
  }

  Future<void> _fillMissingDays() async {
    if (state.isEmpty) return;
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final earliestDate = state.last.date;
    final earliest = DateTime(earliestDate.year, earliestDate.month, earliestDate.day);
    final existingDates = state
        .map((j) => DateTime(j.date.year, j.date.month, j.date.day))
        .toSet();
    final toAdd = <Journal>[];
    var cursor = earliest;
    while (!cursor.isAfter(today)) {
      if (!existingDates.contains(cursor)) {
        final id = 'auto_${cursor.year}${cursor.month.toString().padLeft(2, '0')}${cursor.day.toString().padLeft(2, '0')}';
        toAdd.add(Journal(id: id, date: cursor, content: _kForgotToWrite, createdAt: cursor));
      }
      cursor = cursor.add(const Duration(days: 1));
    }
    if (toAdd.isEmpty) return;
    state = [...state, ...toAdd]..sort((a, b) => b.date.compareTo(a.date));
    if (_isGuest) {
      _persistLocally();
    } else {
      for (final j in toAdd) {
        _upsert(j);
      }
    }
  }

  void clear() {
    _userId = null;
    state = [];
  }

  // Merges only real (non-auto-filled) journals; auto-filled ones are regenerated by _fillMissingDays after load.
  Future<void> mergeToUser(String userId) async {
    _userId = userId;
    for (final j in state.where((j) => !j.id.startsWith('auto_'))) {
      try {
        await _db.from('journals').upsert({...j.toJson(), 'user_id': userId});
      } catch (_) {}
    }
  }

  void _upsert(Journal journal) {
    if (_userId == null || _isGuest) return;
    _db.from('journals')
        .upsert({...journal.toJson(), 'user_id': _userId})
        .catchError((_) {});
  }

  void add(DateTime date, {String? content}) {
    final journal = Journal(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      date: date,
      content: content,
      createdAt: DateTime.now(),
    );
    state = [journal, ...state]..sort((a, b) => b.date.compareTo(a.date));
    if (_isGuest) {
      _persistLocally();
    } else {
      _upsert(journal);
    }
  }

  void update(Journal updated) {
    state = [
      for (final j in state)
        if (j.id == updated.id) updated else j,
    ]..sort((a, b) => b.date.compareTo(a.date));
    if (_isGuest) {
      _persistLocally();
    } else {
      _upsert(updated);
    }
  }

  void remove(String id) {
    state = state.where((j) => j.id != id).toList();
    if (_isGuest) {
      _persistLocally();
    } else if (_userId != null) {
      _db.from('journals').delete().eq('id', id).catchError((_) {});
    }
  }
}

final journalProvider = StateNotifierProvider<JournalNotifier, List<Journal>>(
  (ref) => JournalNotifier(),
);
