import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/journal.dart';
import 'synced_list_notifier.dart';

class JournalNotifier extends SyncedListNotifier<Journal> {
  JournalNotifier(super.ref)
      : super(
          table: 'journals',
          localKey: 'guest_journals',
          orderColumn: 'date',
          orderAscending: false,
        );

  @override
  Journal fromJson(Map<String, dynamic> json) => Journal.fromJson(json);

  @override
  Map<String, dynamic> toJson(Journal item) => item.toJson();

  @override
  String idOf(Journal item) => item.id;

  // Auto-filled rows are regenerated by _fillMissingDays after every load, so
  // merging them would duplicate them under the new account
  @override
  Future<void> mergeToUser(String userId) async {
    final real = state.where((j) => !j.id.startsWith('auto_')).toList();
    state = real;
    await super.mergeToUser(userId);
  }

  @override
  Future<void> afterLoad() => _fillMissingDays();

  static const _kForgotToWrite = '好像忘記什麼了......';

  Future<void> _fillMissingDays() async {
    if (state.isEmpty) return;
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final earliestDate = state.last.date;
    final earliest = DateTime(earliestDate.year, earliestDate.month, earliestDate.day);
    final existingDates = state
        .map((j) => DateTime(j.date.year, j.date.month, j.date.day))
        .toSet();
    final toAdd = <Journal>[];
    var cursor = earliest;
    while (!cursor.isAfter(today)) {
      if (!existingDates.contains(cursor)) {
        final id = 'auto_${cursor.year}${cursor.month.toString().padLeft(2, '0')}${cursor.day.toString().padLeft(2, '0')}';
        toAdd.add(Journal(id: id, date: cursor, content: _kForgotToWrite, createdAt: cursor));
      }
      cursor = cursor.add(const Duration(days: 1));
    }
    if (toAdd.isEmpty) return;
    state = [...state, ...toAdd]..sort((a, b) => b.date.compareTo(a.date));
    if (isGuest) {
      persistLocally();
    } else {
      for (final j in toAdd) {
        upsert(j);
      }
    }
  }

  void add(DateTime date, {String? content}) {
    final journal = Journal(
      id: newRowId(),
      date: date,
      content: content,
      createdAt: DateTime.now(),
    );
    state = [journal, ...state]..sort((a, b) => b.date.compareTo(a.date));
    upsert(journal);
  }

  void update(Journal updated) {
    state = [
      for (final j in state)
        if (j.id == updated.id) updated else j,
    ]..sort((a, b) => b.date.compareTo(a.date));
    upsert(updated);
  }

  void remove(String id) {
    state = state.where((j) => j.id != id).toList();
    deleteRow(id);
  }
}

final journalProvider = StateNotifierProvider<JournalNotifier, List<Journal>>(
  (ref) => JournalNotifier(ref),
);
